apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: horaires-data-pvc
  namespace: horaires-app
  labels:
    app: calcule-horaires
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # DÃ©commentez et modifiez selon votre classe de stockage
  # storageClassName: standard
